name: Github Actions Demo
on: 
  push:
    branches: 
      - main
    paths-ignore: 
      - '.github/**'
      
  pull_request:
    branches: main
    
  schedule:
    - cron: 15 06 * * SUN
  
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        name: Checkut
      - run: echo "${{ github.event_name }}"
      - run: echo "${{ github.ref}}"
      - run: |
          cd ${{ github.workspace }}
          dir
    
  Test:
    runs-on: ubuntu-latest
    needs: [Build]
    if: ${{ github.event_name == 'workflow_dispatch' }}
    environment: Test
    steps:
      - run: echo "Testing..."

  Load-Test:
    runs-on: ubuntu-latest
    needs: [Build]
    if: ${{ github.event_name == 'workflow_dispatch' }}
    environment: Test
    steps:
      - run: |
          echo "Testing..."
          sleep 15
          
  Production:
    runs-on: ubuntu-latest
    needs: [Test, Load-Test]
    if: ${{ github.event.inputs.environment == 'Production' }}    
    environment: 
      name: Production
      url: https://writeabout.net
    steps:
      - run: |
          echo "Step 1 deploying..."      
          sleep 5
      - run: |
          echo "Step 2 deploying..."      
          sleep 5
      - run: |
          echo "Step 3 deploying..."      
          sleep 5
      - run: |
          echo "Step 4 deploying..."      
          sleep 5
      - run: |
          echo "Step 5 deploying..."      
          sleep 5          
          
