name: Github Actions Demo
on: 
  push:
    branches: 
      - main
    paths-ignore: 
      - '.github/**'
      
  pull_request:
    branches: main
    
  schedule:
    - cron: 15 06 * * SUN
  
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        name: Checkut
      - run: echo "${{ github.event.name }}"
      - run: echo" ${{ github.ref}}"
      - run: |
          cd ${{ github.workspace }}
          dir
    
      
      
